[versions]
assertj = "3.27.6"
checkerframework-checker = "3.53.0"
checkerframework-plugin = "0.6.61"
errorprone = "2.46.0"
errorprone-plugin = "4.4.0"
findsecbugs = "1.14.0"
jqwik = "1.9.3"
junit-jupiter = "6.0.2"
nexus-publish = "2.0.0"
openrewrite-plugin = "7.7.0"
pitest-plugin = "1.19.0-rc.3"
spotbugs = "4.9.8"
spotbugs-plugin = "6.4.8"
version-catalog-update-plugin = "1.0.1"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
checkerframework-checker = { module = "org.checkerframework:checker", version.ref = "checkerframework-checker" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
findsecbugs = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

[plugins]
checkerframework = { id = "org.checkerframework", version.ref = "checkerframework-plugin" }
errorprone-plugin = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
pitest-plugin = { id = "info.solidsoft.pitest", version.ref = "pitest-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
version-catalog-update-plugin = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update-plugin" }
